name: 'Trufflehog Check'
description: 'Scan for committed secrets with minimal configuration.'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  branch:
    description: 'Branch to run the check on'
    required: false
  scanArguments:
    description: 'Argument options for scan.'
    required: false
branding:
  icon: 'lock'
  color: 'orange'
